name         'cassandra'
version      '0.2.6'
author       'Jochen Schalanda, Matthieu Simonin, Cake Solutions Ltd.'
license      'Apache 2.0'
project_page 'https://github.com/cakesolutions/puppet-cassandra'
source       'https://github.com/cakesolutions/puppet-cassandra'
summary      'Puppet module to install Apache Cassandra from the DataStax distribution. Forked from msimonin/cassandra'
description  'A Puppet module to install the DataStax Community edition using the official repositories. Forked from msimonin/cassandra.'
dependency   'puppetlabs/stdlib', '>= 3.0.0'
dependency   'puppetlabs/apt', '1.x'
